/** 分类图标库（lucide.dev）：精选适合做分类的图标 + 中文搜索词
 *  name 存 lucide 的 kebab-case 名（如 'gamepad-2'），展示时查表取组件；未设置时回退 Folder
 */
import {
  Activity, Archive, Atom, Banknote, Bell, Bike, Bot, Box, Boxes, Brain, Briefcase, Brush,
  Bug, Building2, Calculator, Calendar, Camera, Car, Cat, Check, Clock, Cloud, CloudRain,
  Code, Coffee, Coins, Compass, Cpu, CreditCard, Crown, Database, Dog, Download, Dumbbell,
  ExternalLink, Eye, Film, Fish, Flag, Flame, Gift, Globe, GraduationCap, Hammer, HardDrive,
  Hash, Headphones, Heart, HeartPulse, House, Image, Inbox, Info, KeyRound, Keyboard,
  Languages, Layers, LayoutDashboard, LayoutGrid, Leaf, Link, Lock, Map, MapPin, Mail,
  Megaphone, MessageCircle, Mic, Monitor, Moon, Music, Newspaper, Package, Palette,
  Paperclip, PenTool, Phone, Plane, Play, Puzzle, QrCode, Rocket, Rss, Scale, Scan, School,
  Search, Send, Server, Settings, Shield, ShieldCheck, ShoppingBag, ShoppingCart, Smartphone,
  Smile, Snowflake, Sparkles, Star, Sun, Tag, Target, Terminal, Ticket, Trash2, TrendingUp,
  Trophy, Tv, Umbrella, Upload, User, Users, Utensils, Wallet, Wifi, Wrench, Zap, BookOpen,
  Gamepad2, FileText, Folder, FolderOpen, Bookmark, Filter, type LucideIcon,
} from 'lucide-react'

export interface CatIconDef {
  name: string // lucide kebab-case 名（存储值）
  label: string // 展示名
  tags: string // 中文搜索词
  Icon: LucideIcon
}

export const CATEGORY_ICONS: CatIconDef[] = [
  { name: 'star', label: 'Star', tags: '星 收藏 重要 推荐', Icon: Star },
  { name: 'heart', label: 'Heart', tags: '心 喜欢 爱好', Icon: Heart },
  { name: 'bookmark', label: 'Bookmark', tags: '书签 收藏 标记', Icon: Bookmark },
  { name: 'flag', label: 'Flag', tags: '旗帜 标记', Icon: Flag },
  { name: 'tag', label: 'Tag', tags: '标签', Icon: Tag },
  { name: 'hash', label: 'Hash', tags: '话题 标签', Icon: Hash },
  { name: 'house', label: 'House', tags: '主页 首页 家', Icon: House },
  { name: 'user', label: 'User', tags: '用户 个人', Icon: User },
  { name: 'users', label: 'Users', tags: '群组 团队 社区', Icon: Users },
  { name: 'settings', label: 'Settings', tags: '设置 配置 工具', Icon: Settings },
  { name: 'bell', label: 'Bell', tags: '通知 提醒', Icon: Bell },
  { name: 'mail', label: 'Mail', tags: '邮件 邮箱', Icon: Mail },
  { name: 'calendar', label: 'Calendar', tags: '日历 日程 时间', Icon: Calendar },
  { name: 'clock', label: 'Clock', tags: '时钟 时间', Icon: Clock },
  { name: 'map-pin', label: 'MapPin', tags: '定位 地图 位置', Icon: MapPin },
  { name: 'phone', label: 'Phone', tags: '电话 通讯', Icon: Phone },
  { name: 'camera', label: 'Camera', tags: '相机 摄影 照片', Icon: Camera },
  { name: 'image', label: 'Image', tags: '图片 图库 照片', Icon: Image },
  { name: 'folder', label: 'Folder', tags: '文件夹 目录 文件', Icon: Folder },
  { name: 'folder-open', label: 'FolderOpen', tags: '文件夹 打开 文件', Icon: FolderOpen },
  { name: 'file-text', label: 'FileText', tags: '文档 笔记 文章', Icon: FileText },
  { name: 'archive', label: 'Archive', tags: '归档 存档', Icon: Archive },
  { name: 'download', label: 'Download', tags: '下载', Icon: Download },
  { name: 'upload', label: 'Upload', tags: '上传 网盘', Icon: Upload },
  { name: 'search', label: 'Search', tags: '搜索 查找 聚合', Icon: Search },
  { name: 'filter', label: 'Filter', tags: '筛选 过滤', Icon: Filter },
  { name: 'link', label: 'Link', tags: '链接 友链', Icon: Link },
  { name: 'external-link', label: 'ExternalLink', tags: '外链 跳转', Icon: ExternalLink },
  { name: 'lock', label: 'Lock', tags: '锁 密码 安全', Icon: Lock },
  { name: 'shield', label: 'Shield', tags: '盾牌 安全 防护', Icon: Shield },
  { name: 'shield-check', label: 'ShieldCheck', tags: '安全 验证 防护', Icon: ShieldCheck },
  { name: 'key-round', label: 'KeyRound', tags: '密钥 密码 API', Icon: KeyRound },
  { name: 'code', label: 'Code', tags: '代码 开发 编程 程序', Icon: Code },
  { name: 'terminal', label: 'Terminal', tags: '终端 命令 开发', Icon: Terminal },
  { name: 'bug', label: 'Bug', tags: '虫子 调试 开发', Icon: Bug },
  { name: 'database', label: 'Database', tags: '数据库 数据', Icon: Database },
  { name: 'server', label: 'Server', tags: '服务器 主机 运维', Icon: Server },
  { name: 'cloud', label: 'Cloud', tags: '云 云盘 服务', Icon: Cloud },
  { name: 'wifi', label: 'Wifi', tags: '网络 无线', Icon: Wifi },
  { name: 'globe', label: 'Globe', tags: '地球 网站 国际', Icon: Globe },
  { name: 'shopping-cart', label: 'ShoppingCart', tags: '购物车 电商 购物', Icon: ShoppingCart },
  { name: 'shopping-bag', label: 'ShoppingBag', tags: '商城 购物 电商', Icon: ShoppingBag },
  { name: 'credit-card', label: 'CreditCard', tags: '银行卡 支付 金融', Icon: CreditCard },
  { name: 'wallet', label: 'Wallet', tags: '钱包 支付', Icon: Wallet },
  { name: 'banknote', label: 'Banknote', tags: '钞票 钱 金融', Icon: Banknote },
  { name: 'coins', label: 'Coins', tags: '硬币 加密 货币', Icon: Coins },
  { name: 'trending-up', label: 'TrendingUp', tags: '趋势 股票 行情', Icon: TrendingUp },
  { name: 'activity', label: 'Activity', tags: '动态 监控 数据', Icon: Activity },
  { name: 'zap', label: 'Zap', tags: '闪电 快捷 工具 效率', Icon: Zap },
  { name: 'flame', label: 'Flame', tags: '火焰 热门', Icon: Flame },
  { name: 'sparkles', label: 'Sparkles', tags: '闪光 AI 魔法 智能', Icon: Sparkles },
  { name: 'bot', label: 'Bot', tags: '机器人 AI 智能 大模型', Icon: Bot },
  { name: 'brain', label: 'Brain', tags: '大脑 AI 智能 思考', Icon: Brain },
  { name: 'rocket', label: 'Rocket', tags: '火箭 启动 加速', Icon: Rocket },
  { name: 'gift', label: 'Gift', tags: '礼物 福利', Icon: Gift },
  { name: 'ticket', label: 'Ticket', tags: '票券 优惠 活动', Icon: Ticket },
  { name: 'gamepad-2', label: 'Gamepad2', tags: '手柄 游戏 娱乐 玩', Icon: Gamepad2 },
  { name: 'palette', label: 'Palette', tags: '调色盘 设计 颜色 画', Icon: Palette },
  { name: 'brush', label: 'Brush', tags: '画笔 绘画 设计', Icon: Brush },
  { name: 'pen-tool', label: 'PenTool', tags: '钢笔 设计 绘图', Icon: PenTool },
  { name: 'music', label: 'Music', tags: '音乐 歌曲 音符', Icon: Music },
  { name: 'headphones', label: 'Headphones', tags: '耳机 音频 播客', Icon: Headphones },
  { name: 'mic', label: 'Mic', tags: '麦克风 直播 语音', Icon: Mic },
  { name: 'film', label: 'Film', tags: '电影 影视 视频', Icon: Film },
  { name: 'tv', label: 'Tv', tags: '电视 追剧 视频', Icon: Tv },
  { name: 'play', label: 'Play', tags: '播放 视频', Icon: Play },
  { name: 'book-open', label: 'BookOpen', tags: '书 阅读 学习 文章', Icon: BookOpen },
  { name: 'newspaper', label: 'Newspaper', tags: '报纸 新闻 资讯', Icon: Newspaper },
  { name: 'rss', label: 'Rss', tags: '订阅 RSS 博客', Icon: Rss },
  { name: 'graduation-cap', label: 'GraduationCap', tags: '学士帽 教育 学习 考试', Icon: GraduationCap },
  { name: 'school', label: 'School', tags: '学校 教育', Icon: School },
  { name: 'briefcase', label: 'Briefcase', tags: '公文包 工作 办公', Icon: Briefcase },
  { name: 'building-2', label: 'Building2', tags: '大楼 公司 企业', Icon: Building2 },
  { name: 'map', label: 'Map', tags: '地图 导航 位置', Icon: Map },
  { name: 'compass', label: 'Compass', tags: '指南针 探索 方向', Icon: Compass },
  { name: 'layers', label: 'Layers', tags: '图层 聚合 平台', Icon: Layers },
  { name: 'layout-grid', label: 'LayoutGrid', tags: '网格 应用 导航', Icon: LayoutGrid },
  { name: 'layout-dashboard', label: 'LayoutDashboard', tags: '面板 仪表 监控', Icon: LayoutDashboard },
  { name: 'box', label: 'Box', tags: '盒子 包裹', Icon: Box },
  { name: 'package', label: 'Package', tags: '包裹 快递 部署', Icon: Package },
  { name: 'boxes', label: 'Boxes', tags: '堆叠 库 存档', Icon: Boxes },
  { name: 'wrench', label: 'Wrench', tags: '扳手 工具 维修', Icon: Wrench },
  { name: 'hammer', label: 'Hammer', tags: '锤子 工具', Icon: Hammer },
  { name: 'cpu', label: 'Cpu', tags: '处理器 硬件 芯片', Icon: Cpu },
  { name: 'hard-drive', label: 'HardDrive', tags: '硬盘 存储', Icon: HardDrive },
  { name: 'monitor', label: 'Monitor', tags: '显示器 电脑 软件', Icon: Monitor },
  { name: 'smartphone', label: 'Smartphone', tags: '手机 移动 应用', Icon: Smartphone },
  { name: 'keyboard', label: 'Keyboard', tags: '键盘 输入', Icon: Keyboard },
  { name: 'scan', label: 'Scan', tags: '扫描 识别', Icon: Scan },
  { name: 'qr-code', label: 'QrCode', tags: '二维码', Icon: QrCode },
  { name: 'coffee', label: 'Coffee', tags: '咖啡 休闲 下午茶', Icon: Coffee },
  { name: 'utensils', label: 'Utensils', tags: '餐具 美食 吃', Icon: Utensils },
  { name: 'smile', label: 'Smile', tags: '表情 开心 娱乐', Icon: Smile },
  { name: 'sun', label: 'Sun', tags: '太阳 天气 白天', Icon: Sun },
  { name: 'moon', label: 'Moon', tags: '月亮 夜间 睡眠', Icon: Moon },
  { name: 'cloud-rain', label: 'CloudRain', tags: '雨 天气', Icon: CloudRain },
  { name: 'snowflake', label: 'Snowflake', tags: '雪花 冬天 天气', Icon: Snowflake },
  { name: 'umbrella', label: 'Umbrella', tags: '雨伞 天气', Icon: Umbrella },
  { name: 'car', label: 'Car', tags: '汽车 出行 自驾', Icon: Car },
  { name: 'plane', label: 'Plane', tags: '飞机 旅行 机票', Icon: Plane },
  { name: 'bike', label: 'Bike', tags: '自行车 骑行 运动', Icon: Bike },
  { name: 'heart-pulse', label: 'HeartPulse', tags: '心率 健康 运动 医疗', Icon: HeartPulse },
  { name: 'dumbbell', label: 'Dumbbell', tags: '哑铃 健身 运动', Icon: Dumbbell },
  { name: 'trophy', label: 'Trophy', tags: '奖杯 排行 获奖', Icon: Trophy },
  { name: 'crown', label: 'Crown', tags: '皇冠 VIP 精选', Icon: Crown },
  { name: 'target', label: 'Target', tags: '目标 靶心', Icon: Target },
  { name: 'puzzle', label: 'Puzzle', tags: '拼图 插件 扩展', Icon: Puzzle },
  { name: 'dog', label: 'Dog', tags: '狗 宠物', Icon: Dog },
  { name: 'cat', label: 'Cat', tags: '猫 宠物', Icon: Cat },
  { name: 'fish', label: 'Fish', tags: '鱼 宠物 水族', Icon: Fish },
  { name: 'leaf', label: 'Leaf', tags: '叶子 环保 植物', Icon: Leaf },
  { name: 'atom', label: 'Atom', tags: '原子 科学', Icon: Atom },
  { name: 'scale', label: 'Scale', tags: '天平 法律 公正', Icon: Scale },
  { name: 'languages', label: 'Languages', tags: '语言 翻译 学习', Icon: Languages },
  { name: 'calculator', label: 'Calculator', tags: '计算器 计算 工具', Icon: Calculator },
  { name: 'send', label: 'Send', tags: '发送 邮件', Icon: Send },
  { name: 'inbox', label: 'Inbox', tags: '收件箱 邮箱', Icon: Inbox },
  { name: 'megaphone', label: 'Megaphone', tags: '喇叭 公告 营销', Icon: Megaphone },
  { name: 'check', label: 'Check', tags: '对勾 完成', Icon: Check },
  { name: 'info', label: 'Info', tags: '信息 说明 帮助', Icon: Info },
  { name: 'eye', label: 'Eye', tags: '眼睛 查看 观察站', Icon: Eye },
  { name: 'paperclip', label: 'Paperclip', tags: '回形针 附件 资源', Icon: Paperclip },
  { name: 'trash-2', label: 'Trash2', tags: '垃圾桶 删除 回收', Icon: Trash2 },
]

const ICON_MAP: Record<string, CatIconDef> = {}
for (const d of CATEGORY_ICONS) ICON_MAP[d.name] = d

/** 按存储名取图标；未设置 / 名字未知时回退 Folder */
export function categoryIcon(name?: string): LucideIcon {
  const hit = name ? ICON_MAP[name] : undefined
  return hit ? hit.Icon : Folder
}

/** 名字对应的展示名（未设置返回空串） */
export function categoryIconLabel(name?: string): string {
  const hit = name ? ICON_MAP[name] : undefined
  return hit ? hit.label : ''
}
